name: "Pyrite Cloud Redeploy Action"
description: "This action redeploys the deployment on Pyrite Cloud."
author: "Ayush Chothe"

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  token:
    description: "Pyrite Cloud token for specific deployment"
    required: true

branding:
  icon: refresh-cw
  color: "green"