name: redeploy

on:
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Redeploy Deployment
        uses: ./
        with:
          token: ${{ secrets.PYRITE_TOKEN }}
